# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoiDungManHinhCaiDatHeThong.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_containSettingContent(object):
    def setupUi(self, widget_containSettingContent):
        widget_containSettingContent.setObjectName("widget_containSettingContent")
        widget_containSettingContent.resize(416, 1900)
        self.frame_serverInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_serverInfomation.setGeometry(QtCore.QRect(0, 300, 421, 261))
        self.frame_serverInfomation.setStyleSheet("border: 0px")
        self.frame_serverInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_serverInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_serverInfomation.setObjectName("frame_serverInfomation")
        self.label_ctThongTinCuavv = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_ctThongTinCuavv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctThongTinCuavv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctThongTinCuavv.setWordWrap(True)
        self.label_ctThongTinCuavv.setObjectName("label_ctThongTinCuavv")
        self.label_diaChi = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_diaChi.setGeometry(QtCore.QRect(40, 60, 81, 17))
        self.label_diaChi.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi.setObjectName("label_diaChi")
        self.lineEdit_forInputIP = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputIP.setGeometry(QtCore.QRect(130, 50, 221, 30))
        self.lineEdit_forInputIP.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputIP.setObjectName("lineEdit_forInputIP")
        self.label_cong = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_cong.setGeometry(QtCore.QRect(40, 100, 81, 17))
        self.label_cong.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_cong.setObjectName("label_cong")
        self.lineEdit_forInputPort = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputPort.setGeometry(QtCore.QRect(130, 90, 221, 30))
        self.lineEdit_forInputPort.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputPort.setObjectName("lineEdit_forInputPort")
        self.lineEdit_forInputAccount = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputAccount.setGeometry(QtCore.QRect(130, 130, 221, 30))
        self.lineEdit_forInputAccount.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputAccount.setObjectName("lineEdit_forInputAccount")
        self.label_taiKhoan = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_taiKhoan.setGeometry(QtCore.QRect(40, 140, 81, 17))
        self.label_taiKhoan.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_taiKhoan.setObjectName("label_taiKhoan")
        self.lineEdit_forInputPassword = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputPassword.setGeometry(QtCore.QRect(130, 170, 221, 30))
        self.lineEdit_forInputPassword.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputPassword.setObjectName("lineEdit_forInputPassword")
        self.label_matKhau = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_matKhau.setGeometry(QtCore.QRect(40, 180, 81, 17))
        self.label_matKhau.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_matKhau.setObjectName("label_matKhau")
        self.label_diaChi_2 = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_diaChi_2.setGeometry(QtCore.QRect(10, 6, 241, 16))
        self.label_diaChi_2.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_diaChi_2.setObjectName("label_diaChi_2")
        self.label_iconCheckServerIP = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerIP.setGeometry(QtCore.QRect(368, 50, 23, 29))
        self.label_iconCheckServerIP.setText("")
        self.label_iconCheckServerIP.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerIP.setObjectName("label_iconCheckServerIP")
        self.label_iconCheckServerPort = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerPort.setGeometry(QtCore.QRect(368, 90, 25, 25))
        self.label_iconCheckServerPort.setText("")
        self.label_iconCheckServerPort.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerPort.setObjectName("label_iconCheckServerPort")
        self.label_iconCheckServerAccount = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerAccount.setGeometry(QtCore.QRect(368, 130, 25, 25))
        self.label_iconCheckServerAccount.setText("")
        self.label_iconCheckServerAccount.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerAccount.setObjectName("label_iconCheckServerAccount")
        self.label_iconCheckServerPassword = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerPassword.setGeometry(QtCore.QRect(368, 170, 25, 25))
        self.label_iconCheckServerPassword.setText("")
        self.label_iconCheckServerPassword.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerPassword.setObjectName("label_iconCheckServerPassword")
        self.pushButton_connectNewServer = QtWidgets.QPushButton(self.frame_serverInfomation)
        self.pushButton_connectNewServer.setGeometry(QtCore.QRect(300, 210, 101, 41))
        self.pushButton_connectNewServer.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../Downloads/iconConnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_connectNewServer.setIcon(icon)
        self.pushButton_connectNewServer.setObjectName("pushButton_connectNewServer")
        self.label_showSocketConnectStatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_showSocketConnectStatus.setGeometry(QtCore.QRect(70, 210, 221, 45))
        self.label_showSocketConnectStatus.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_showSocketConnectStatus.setText("")
        self.label_showSocketConnectStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_showSocketConnectStatus.setWordWrap(True)
        self.label_showSocketConnectStatus.setObjectName("label_showSocketConnectStatus")
        self.label_iconSocketStatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconSocketStatus.setGeometry(QtCore.QRect(8, 220, 39, 37))
        self.label_iconSocketStatus.setText("")
        self.label_iconSocketStatus.setObjectName("label_iconSocketStatus")
        self.frame_containFTPserverInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFTPserverInfomation.setGeometry(QtCore.QRect(0, 570, 421, 271))
        self.frame_containFTPserverInfomation.setStyleSheet("border: 0px")
        self.frame_containFTPserverInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFTPserverInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFTPserverInfomation.setObjectName("frame_containFTPserverInfomation")
        self.label_thongTinMayChuDuLieu = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_thongTinMayChuDuLieu.setGeometry(QtCore.QRect(10, 0, 391, 21))
        self.label_thongTinMayChuDuLieu.setMouseTracking(True)
        self.label_thongTinMayChuDuLieu.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_thongTinMayChuDuLieu.setWordWrap(True)
        self.label_thongTinMayChuDuLieu.setObjectName("label_thongTinMayChuDuLieu")
        self.label_ctThongTinMayvv = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_ctThongTinMayvv.setGeometry(QtCore.QRect(10, 20, 391, 21))
        self.label_ctThongTinMayvv.setMouseTracking(True)
        self.label_ctThongTinMayvv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctThongTinMayvv.setWordWrap(True)
        self.label_ctThongTinMayvv.setObjectName("label_ctThongTinMayvv")
        self.label_diaChiIPFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_diaChiIPFTP.setGeometry(QtCore.QRect(40, 70, 81, 17))
        self.label_diaChiIPFTP.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChiIPFTP.setObjectName("label_diaChiIPFTP")
        self.lineEdit_forInputFTPIP = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPIP.setGeometry(QtCore.QRect(130, 50, 221, 30))
        self.lineEdit_forInputFTPIP.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputFTPIP.setObjectName("lineEdit_forInputFTPIP")
        self.label_congFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_congFTP.setGeometry(QtCore.QRect(40, 100, 81, 17))
        self.label_congFTP.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_congFTP.setObjectName("label_congFTP")
        self.lineEdit_forInputFTPport = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPport.setGeometry(QtCore.QRect(130, 90, 221, 30))
        self.lineEdit_forInputFTPport.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputFTPport.setText("")
        self.lineEdit_forInputFTPport.setObjectName("lineEdit_forInputFTPport")
        self.lineEdit_forInputFTPaccount = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPaccount.setGeometry(QtCore.QRect(130, 130, 221, 30))
        self.lineEdit_forInputFTPaccount.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputFTPaccount.setObjectName("lineEdit_forInputFTPaccount")
        self.label_taiKhoanFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_taiKhoanFTP.setGeometry(QtCore.QRect(40, 130, 81, 17))
        self.label_taiKhoanFTP.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_taiKhoanFTP.setObjectName("label_taiKhoanFTP")
        self.lineEdit_forInputFPTpassword = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFPTpassword.setGeometry(QtCore.QRect(130, 170, 221, 30))
        self.lineEdit_forInputFPTpassword.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputFPTpassword.setObjectName("lineEdit_forInputFPTpassword")
        self.label_matKhauFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_matKhauFTP.setGeometry(QtCore.QRect(40, 160, 81, 17))
        self.label_matKhauFTP.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_matKhauFTP.setObjectName("label_matKhauFTP")
        self.label_iconCheckFTPip = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_iconCheckFTPip.setGeometry(QtCore.QRect(366, 50, 25, 25))
        self.label_iconCheckFTPip.setText("")
        self.label_iconCheckFTPip.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckFTPip.setObjectName("label_iconCheckFTPip")
        self.label_iconCheckFTPaccount = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_iconCheckFTPaccount.setGeometry(QtCore.QRect(366, 130, 23, 25))
        self.label_iconCheckFTPaccount.setText("")
        self.label_iconCheckFTPaccount.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckFTPaccount.setObjectName("label_iconCheckFTPaccount")
        self.label_iconCheckFTPpassword = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_iconCheckFTPpassword.setGeometry(QtCore.QRect(366, 170, 23, 25))
        self.label_iconCheckFTPpassword.setText("")
        self.label_iconCheckFTPpassword.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckFTPpassword.setObjectName("label_iconCheckFTPpassword")
        self.label_iconCheckFTPport = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_iconCheckFTPport.setGeometry(QtCore.QRect(366, 90, 25, 25))
        self.label_iconCheckFTPport.setText("")
        self.label_iconCheckFTPport.setPixmap(QtGui.QPixmap("../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckFTPport.setObjectName("label_iconCheckFTPport")
        self.pushButton_connectNewFTP = QtWidgets.QPushButton(self.frame_containFTPserverInfomation)
        self.pushButton_connectNewFTP.setGeometry(QtCore.QRect(300, 210, 101, 41))
        self.pushButton_connectNewFTP.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_connectNewFTP.setIcon(icon)
        self.pushButton_connectNewFTP.setObjectName("pushButton_connectNewFTP")
        self.label_showFTPconnectStatus = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_showFTPconnectStatus.setGeometry(QtCore.QRect(70, 210, 221, 45))
        self.label_showFTPconnectStatus.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_showFTPconnectStatus.setText("")
        self.label_showFTPconnectStatus.setObjectName("label_showFTPconnectStatus")
        self.label_forShowIconFTPstatus = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_forShowIconFTPstatus.setGeometry(QtCore.QRect(6, 220, 39, 37))
        self.label_forShowIconFTPstatus.setText("")
        self.label_forShowIconFTPstatus.setObjectName("label_forShowIconFTPstatus")
        self.frame_containMemoryInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containMemoryInfomation.setGeometry(QtCore.QRect(0, 1320, 421, 149))
        self.frame_containMemoryInfomation.setStyleSheet("border: 0px")
        self.frame_containMemoryInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containMemoryInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containMemoryInfomation.setObjectName("frame_containMemoryInfomation")
        self.label_thongTinBoNho = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_thongTinBoNho.setGeometry(QtCore.QRect(10, 12, 391, 21))
        self.label_thongTinBoNho.setMouseTracking(True)
        self.label_thongTinBoNho.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_thongTinBoNho.setWordWrap(True)
        self.label_thongTinBoNho.setObjectName("label_thongTinBoNho")
        self.label_ctBoNhoSuvv = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_ctBoNhoSuvv.setGeometry(QtCore.QRect(10, 34, 391, 21))
        self.label_ctBoNhoSuvv.setMouseTracking(True)
        self.label_ctBoNhoSuvv.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctBoNhoSuvv.setWordWrap(True)
        self.label_ctBoNhoSuvv.setObjectName("label_ctBoNhoSuvv")
        self.pushButton_deleteAllData = QtWidgets.QPushButton(self.frame_containMemoryInfomation)
        self.pushButton_deleteAllData.setGeometry(QtCore.QRect(22, 66, 65, 31))
        self.pushButton_deleteAllData.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_deleteAllData.setObjectName("pushButton_deleteAllData")
        self.frame_containFirmwareInformation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFirmwareInformation.setGeometry(QtCore.QRect(10, 1490, 421, 265))
        self.frame_containFirmwareInformation.setStyleSheet("border: 0px")
        self.frame_containFirmwareInformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFirmwareInformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFirmwareInformation.setObjectName("frame_containFirmwareInformation")
        self.label_phienBanPhanMem = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_phienBanPhanMem.setGeometry(QtCore.QRect(10, 12, 391, 21))
        self.label_phienBanPhanMem.setMouseTracking(True)
        self.label_phienBanPhanMem.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_phienBanPhanMem.setWordWrap(True)
        self.label_phienBanPhanMem.setObjectName("label_phienBanPhanMem")
        self.label_ctPHanMemTrenvv = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_ctPHanMemTrenvv.setGeometry(QtCore.QRect(10, 38, 391, 25))
        self.label_ctPHanMemTrenvv.setMouseTracking(True)
        self.label_ctPHanMemTrenvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctPHanMemTrenvv.setWordWrap(True)
        self.label_ctPHanMemTrenvv.setObjectName("label_ctPHanMemTrenvv")
        self.pushButton_checkUpdate = QtWidgets.QPushButton(self.frame_containFirmwareInformation)
        self.pushButton_checkUpdate.setGeometry(QtCore.QRect(20, 178, 151, 59))
        self.pushButton_checkUpdate.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(214, 214, 160);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);\n"
"")
        self.pushButton_checkUpdate.setObjectName("pushButton_checkUpdate")
        self.layoutWidget = QtWidgets.QWidget(self.frame_containFirmwareInformation)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 82, 134, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_phienBan = QtWidgets.QLabel(self.layoutWidget)
        self.label_phienBan.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_phienBan.setObjectName("label_phienBan")
        self.verticalLayout.addWidget(self.label_phienBan)
        self.label_ngayGioCapNhat = QtWidgets.QLabel(self.layoutWidget)
        self.label_ngayGioCapNhat.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_ngayGioCapNhat.setObjectName("label_ngayGioCapNhat")
        self.verticalLayout.addWidget(self.label_ngayGioCapNhat)
        self.label_banQuyen = QtWidgets.QLabel(self.layoutWidget)
        self.label_banQuyen.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_banQuyen.setObjectName("label_banQuyen")
        self.verticalLayout.addWidget(self.label_banQuyen)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_containFirmwareInformation)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 80, 171, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_forShowFirmwareVersion = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowFirmwareVersion.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_forShowFirmwareVersion.setObjectName("label_forShowFirmwareVersion")
        self.verticalLayout_2.addWidget(self.label_forShowFirmwareVersion)
        self.label_forShowUpdateTime = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowUpdateTime.setText("")
        self.label_forShowUpdateTime.setObjectName("label_forShowUpdateTime")
        self.verticalLayout_2.addWidget(self.label_forShowUpdateTime)
        self.label_forShowCopyright = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowCopyright.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_forShowCopyright.setWordWrap(True)
        self.label_forShowCopyright.setObjectName("label_forShowCopyright")
        self.verticalLayout_2.addWidget(self.label_forShowCopyright)
        self.line_3 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_3.setGeometry(QtCore.QRect(20, 60, 371, 1))
        self.line_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_4.setGeometry(QtCore.QRect(20, 290, 371, 1))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_5.setGeometry(QtCore.QRect(20, 560, 371, 1))
        self.line_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_7.setGeometry(QtCore.QRect(22, 830, 371, 1))
        self.line_7.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label = QtWidgets.QLabel(widget_containSettingContent)
        self.label.setGeometry(QtCore.QRect(148, 10, 189, 39))
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("font: 75 bold 18pt \"Ubuntu\";\n"
"color: rgb(85, 85, 0);")
        self.label.setObjectName("label")
        self.frame_containFaceRecognitionPoint = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFaceRecognitionPoint.setGeometry(QtCore.QRect(0, 830, 421, 131))
        self.frame_containFaceRecognitionPoint.setStyleSheet("border: 0px")
        self.frame_containFaceRecognitionPoint.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFaceRecognitionPoint.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFaceRecognitionPoint.setObjectName("frame_containFaceRecognitionPoint")
        self.label_doChinhXacNhanDienvv = QtWidgets.QLabel(self.frame_containFaceRecognitionPoint)
        self.label_doChinhXacNhanDienvv.setGeometry(QtCore.QRect(10, 8, 393, 25))
        self.label_doChinhXacNhanDienvv.setMouseTracking(True)
        self.label_doChinhXacNhanDienvv.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_doChinhXacNhanDienvv.setWordWrap(True)
        self.label_doChinhXacNhanDienvv.setObjectName("label_doChinhXacNhanDienvv")
        self.label_ctTangDoChinhXacvv = QtWidgets.QLabel(self.frame_containFaceRecognitionPoint)
        self.label_ctTangDoChinhXacvv.setGeometry(QtCore.QRect(10, 38, 391, 41))
        self.label_ctTangDoChinhXacvv.setMouseTracking(True)
        self.label_ctTangDoChinhXacvv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctTangDoChinhXacvv.setWordWrap(True)
        self.label_ctTangDoChinhXacvv.setObjectName("label_ctTangDoChinhXacvv")
        self.comboBox_forChooseFRPoint = QtWidgets.QComboBox(self.frame_containFaceRecognitionPoint)
        self.comboBox_forChooseFRPoint.setGeometry(QtCore.QRect(14, 90, 161, 31))
        self.comboBox_forChooseFRPoint.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_forChooseFRPoint.setObjectName("comboBox_forChooseFRPoint")
        self.comboBox_forChooseFRPoint.addItem("")
        self.comboBox_forChooseFRPoint.addItem("")
        self.comboBox_forChooseFRPoint.addItem("")
        self.comboBox_forChooseFRPoint.addItem("")
        self.comboBox_forChooseFRPoint.addItem("")
        self.comboBox_forChooseFRPoint.addItem("")
        self.frame_imageQuality = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_imageQuality.setGeometry(QtCore.QRect(0, 960, 421, 195))
        self.frame_imageQuality.setStyleSheet("border: 0px")
        self.frame_imageQuality.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_imageQuality.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_imageQuality.setObjectName("frame_imageQuality")
        self.label_anhTaiLenTrungTam = QtWidgets.QLabel(self.frame_imageQuality)
        self.label_anhTaiLenTrungTam.setGeometry(QtCore.QRect(10, 8, 393, 25))
        self.label_anhTaiLenTrungTam.setMouseTracking(True)
        self.label_anhTaiLenTrungTam.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_anhTaiLenTrungTam.setWordWrap(True)
        self.label_anhTaiLenTrungTam.setObjectName("label_anhTaiLenTrungTam")
        self.label_ctLuaChonChatLuongvv = QtWidgets.QLabel(self.frame_imageQuality)
        self.label_ctLuaChonChatLuongvv.setGeometry(QtCore.QRect(10, 32, 391, 41))
        self.label_ctLuaChonChatLuongvv.setMouseTracking(True)
        self.label_ctLuaChonChatLuongvv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctLuaChonChatLuongvv.setWordWrap(True)
        self.label_ctLuaChonChatLuongvv.setObjectName("label_ctLuaChonChatLuongvv")
        self.comboBox_forChooserImageQuality = QtWidgets.QComboBox(self.frame_imageQuality)
        self.comboBox_forChooserImageQuality.setGeometry(QtCore.QRect(14, 72, 161, 31))
        self.comboBox_forChooserImageQuality.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_forChooserImageQuality.setObjectName("comboBox_forChooserImageQuality")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooserImageQuality.addItem("")
        self.comboBox_forChooseFaceMark = QtWidgets.QComboBox(self.frame_imageQuality)
        self.comboBox_forChooseFaceMark.setGeometry(QtCore.QRect(14, 148, 161, 31))
        self.comboBox_forChooseFaceMark.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_forChooseFaceMark.setObjectName("comboBox_forChooseFaceMark")
        self.comboBox_forChooseFaceMark.addItem("")
        self.comboBox_forChooseFaceMark.addItem("")
        self.label_coKhoanhKhuonMat = QtWidgets.QLabel(self.frame_imageQuality)
        self.label_coKhoanhKhuonMat.setGeometry(QtCore.QRect(8, 104, 391, 41))
        self.label_coKhoanhKhuonMat.setMouseTracking(True)
        self.label_coKhoanhKhuonMat.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_coKhoanhKhuonMat.setWordWrap(True)
        self.label_coKhoanhKhuonMat.setObjectName("label_coKhoanhKhuonMat")
        self.line_9 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_9.setGeometry(QtCore.QRect(22, 960, 371, 1))
        self.line_9.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_10.setGeometry(QtCore.QRect(24, 1160, 371, 1))
        self.line_10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_11.setGeometry(QtCore.QRect(20, 1470, 371, 1))
        self.line_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.frame_containMemoryInfomation_2 = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containMemoryInfomation_2.setGeometry(QtCore.QRect(0, 1170, 421, 149))
        self.frame_containMemoryInfomation_2.setStyleSheet("border: 0px")
        self.frame_containMemoryInfomation_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containMemoryInfomation_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containMemoryInfomation_2.setObjectName("frame_containMemoryInfomation_2")
        self.label_lamSachCamBien = QtWidgets.QLabel(self.frame_containMemoryInfomation_2)
        self.label_lamSachCamBien.setGeometry(QtCore.QRect(10, 12, 391, 21))
        self.label_lamSachCamBien.setMouseTracking(True)
        self.label_lamSachCamBien.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_lamSachCamBien.setWordWrap(True)
        self.label_lamSachCamBien.setObjectName("label_lamSachCamBien")
        self.label_xoaBoRacCamBien = QtWidgets.QLabel(self.frame_containMemoryInfomation_2)
        self.label_xoaBoRacCamBien.setGeometry(QtCore.QRect(10, 34, 391, 21))
        self.label_xoaBoRacCamBien.setMouseTracking(True)
        self.label_xoaBoRacCamBien.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_xoaBoRacCamBien.setWordWrap(True)
        self.label_xoaBoRacCamBien.setObjectName("label_xoaBoRacCamBien")
        self.pushButton_cleanFGPsensor = QtWidgets.QPushButton(self.frame_containMemoryInfomation_2)
        self.pushButton_cleanFGPsensor.setGeometry(QtCore.QRect(24, 72, 137, 59))
        self.pushButton_cleanFGPsensor.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_cleanFGPsensor.setObjectName("pushButton_cleanFGPsensor")
        self.line_12 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_12.setGeometry(QtCore.QRect(24, 1320, 371, 1))
        self.line_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.frame_autoShutdown = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_autoShutdown.setGeometry(QtCore.QRect(0, 1770, 421, 123))
        self.frame_autoShutdown.setStyleSheet("border: 0px")
        self.frame_autoShutdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_autoShutdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_autoShutdown.setObjectName("frame_autoShutdown")
        self.label_tuDongTat_2 = QtWidgets.QLabel(self.frame_autoShutdown)
        self.label_tuDongTat_2.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_tuDongTat_2.setMouseTracking(True)
        self.label_tuDongTat_2.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_tuDongTat_2.setWordWrap(True)
        self.label_tuDongTat_2.setObjectName("label_tuDongTat_2")
        self.label_ctTuDongTatvv_2 = QtWidgets.QLabel(self.frame_autoShutdown)
        self.label_ctTuDongTatvv_2.setGeometry(QtCore.QRect(10, 30, 391, 47))
        self.label_ctTuDongTatvv_2.setMouseTracking(True)
        self.label_ctTuDongTatvv_2.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctTuDongTatvv_2.setWordWrap(True)
        self.label_ctTuDongTatvv_2.setObjectName("label_ctTuDongTatvv_2")
        self.comboBox_chooseTime = QtWidgets.QComboBox(self.frame_autoShutdown)
        self.comboBox_chooseTime.setGeometry(QtCore.QRect(10, 84, 161, 31))
        self.comboBox_chooseTime.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_chooseTime.setObjectName("comboBox_chooseTime")
        self.line_6 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_6.setGeometry(QtCore.QRect(20, 1760, 371, 1))
        self.line_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_diaChi_4 = QtWidgets.QLabel(widget_containSettingContent)
        self.label_diaChi_4.setGeometry(QtCore.QRect(30, 110, 81, 17))
        self.label_diaChi_4.setText("")
        self.label_diaChi_4.setObjectName("label_diaChi_4")
        self.frame_autoShutdown_2 = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_autoShutdown_2.setGeometry(QtCore.QRect(0, 60, 421, 231))
        self.frame_autoShutdown_2.setStyleSheet("border: 0px")
        self.frame_autoShutdown_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_autoShutdown_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_autoShutdown_2.setObjectName("frame_autoShutdown_2")
        self.label_gateway = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_gateway.setGeometry(QtCore.QRect(160, 130, 221, 27))
        self.label_gateway.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_gateway.setText("")
        self.label_gateway.setObjectName("label_gateway")
        self.label_diaChi_6 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_6.setGeometry(QtCore.QRect(30, 139, 121, 21))
        self.label_diaChi_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_6.setObjectName("label_diaChi_6")
        self.label_diaChi_5 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_5.setGeometry(QtCore.QRect(30, 110, 111, 20))
        self.label_diaChi_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_5.setObjectName("label_diaChi_5")
        self.label_subnetMask = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_subnetMask.setGeometry(QtCore.QRect(160, 100, 221, 27))
        self.label_subnetMask.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_subnetMask.setText("")
        self.label_subnetMask.setObjectName("label_subnetMask")
        self.label_diaChi_3 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_3.setGeometry(QtCore.QRect(30, 80, 91, 20))
        self.label_diaChi_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_3.setObjectName("label_diaChi_3")
        self.label_currentIP = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_currentIP.setGeometry(QtCore.QRect(160, 70, 221, 27))
        self.label_currentIP.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_currentIP.setText("")
        self.label_currentIP.setObjectName("label_currentIP")
        self.label_ctThongTinCuavv_2 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_ctThongTinCuavv_2.setGeometry(QtCore.QRect(20, 34, 391, 21))
        self.label_ctThongTinCuavv_2.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctThongTinCuavv_2.setWordWrap(True)
        self.label_ctThongTinCuavv_2.setObjectName("label_ctThongTinCuavv_2")
        self.label_diaChi_7 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_7.setGeometry(QtCore.QRect(20, 10, 231, 17))
        self.label_diaChi_7.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_diaChi_7.setObjectName("label_diaChi_7")
        self.comboBox_choseIpMethod = QtWidgets.QComboBox(self.frame_autoShutdown_2)
        self.comboBox_choseIpMethod.setGeometry(QtCore.QRect(160, 176, 141, 31))
        self.comboBox_choseIpMethod.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox_choseIpMethod.setObjectName("comboBox_choseIpMethod")
        self.comboBox_choseIpMethod.addItem("")
        self.comboBox_choseIpMethod.addItem("")
        self.pushButton_setManualIP = QtWidgets.QPushButton(self.frame_autoShutdown_2)
        self.pushButton_setManualIP.setGeometry(QtCore.QRect(310, 170, 91, 41))
        self.pushButton_setManualIP.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_setManualIP.setObjectName("pushButton_setManualIP")
        self.label_diaChi_8 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_8.setGeometry(QtCore.QRect(30, 180, 121, 21))
        self.label_diaChi_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_8.setObjectName("label_diaChi_8")

        self.retranslateUi(widget_containSettingContent)
        QtCore.QMetaObject.connectSlotsByName(widget_containSettingContent)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputPassword, self.lineEdit_forInputFTPIP)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPIP, self.lineEdit_forInputFTPport)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPport, self.lineEdit_forInputAccount)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputAccount, self.lineEdit_forInputIP)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputIP, self.lineEdit_forInputPort)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputPort, self.lineEdit_forInputFTPaccount)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPaccount, self.lineEdit_forInputFPTpassword)

    def retranslateUi(self, widget_containSettingContent):
        _translate = QtCore.QCoreApplication.translate
        widget_containSettingContent.setWindowTitle(_translate("widget_containSettingContent", "Form"))
        self.label_ctThongTinCuavv.setText(_translate("widget_containSettingContent", "(Thông tin của máy chủ trung tâm điều khiển thiết bị) "))
        self.label_diaChi.setText(_translate("widget_containSettingContent", "Địa chỉ IP"))
        self.label_cong.setText(_translate("widget_containSettingContent", "Cổng"))
        self.label_taiKhoan.setText(_translate("widget_containSettingContent", "Tài khoản"))
        self.label_matKhau.setText(_translate("widget_containSettingContent", "Mật khẩu"))
        self.label_diaChi_2.setText(_translate("widget_containSettingContent", "Thông tin máy chủ"))
        self.pushButton_connectNewServer.setText(_translate("widget_containSettingContent", "Kết nối"))
        self.label_thongTinMayChuDuLieu.setText(_translate("widget_containSettingContent", "Thông tin máy chủ dữ liệu"))
        self.label_ctThongTinMayvv.setText(_translate("widget_containSettingContent", "(Thông tin của máy chủ FTP) "))
        self.label_diaChiIPFTP.setText(_translate("widget_containSettingContent", "Địa chỉ IP"))
        self.label_congFTP.setText(_translate("widget_containSettingContent", "Cổng"))
        self.label_taiKhoanFTP.setText(_translate("widget_containSettingContent", "Tài khoản"))
        self.label_matKhauFTP.setText(_translate("widget_containSettingContent", "Mật khẩu"))
        self.pushButton_connectNewFTP.setText(_translate("widget_containSettingContent", "Kết nối"))
        self.label_thongTinBoNho.setText(_translate("widget_containSettingContent", "Xóa toàn bộ dữ liệu"))
        self.label_ctBoNhoSuvv.setText(_translate("widget_containSettingContent", "(Xóa toàn bộ dữ liệu trên cảm biến)"))
        self.pushButton_deleteAllData.setText(_translate("widget_containSettingContent", "Xóa"))
        self.label_phienBanPhanMem.setText(_translate("widget_containSettingContent", "Phiên bản phần mềm"))
        self.label_ctPHanMemTrenvv.setText(_translate("widget_containSettingContent", "(Phần mềm của thiết bị)"))
        self.pushButton_checkUpdate.setText(_translate("widget_containSettingContent", "Kiểm tra cập nhật"))
        self.label_phienBan.setText(_translate("widget_containSettingContent", "Phiên bản:"))
        self.label_ngayGioCapNhat.setText(_translate("widget_containSettingContent", "Cập nhật ngày, giờ:"))
        self.label_banQuyen.setText(_translate("widget_containSettingContent", "Bản quyền:"))
        self.label_forShowFirmwareVersion.setText(_translate("widget_containSettingContent", "v0.0.0"))
        self.label_forShowCopyright.setText(_translate("widget_containSettingContent", "Công ty cổ phần Công nghệ và Kỹ thuật Ecotek"))
        self.label.setText(_translate("widget_containSettingContent", "HỆ THỐNG"))
        self.label_doChinhXacNhanDienvv.setText(_translate("widget_containSettingContent", "Độ chính xác nhận diện khuôn mặt"))
        self.label_ctTangDoChinhXacvv.setText(_translate("widget_containSettingContent", "(Tăng độ chính xác khi nhận diện khuôn mặt nhưng làm giảm tốc độ nhận diện)"))
        self.comboBox_forChooseFRPoint.setItemText(0, _translate("widget_containSettingContent", "1"))
        self.comboBox_forChooseFRPoint.setItemText(1, _translate("widget_containSettingContent", "2"))
        self.comboBox_forChooseFRPoint.setItemText(2, _translate("widget_containSettingContent", "3"))
        self.comboBox_forChooseFRPoint.setItemText(3, _translate("widget_containSettingContent", "4"))
        self.comboBox_forChooseFRPoint.setItemText(4, _translate("widget_containSettingContent", "5"))
        self.comboBox_forChooseFRPoint.setItemText(5, _translate("widget_containSettingContent", "6"))
        self.label_anhTaiLenTrungTam.setText(_translate("widget_containSettingContent", "Ảnh gửi lên trung tâm"))
        self.label_ctLuaChonChatLuongvv.setText(_translate("widget_containSettingContent", "(Lựa chọn chất lượng ảnh gửi lên khi nhận diện học viên)"))
        self.comboBox_forChooserImageQuality.setItemText(0, _translate("widget_containSettingContent", "1"))
        self.comboBox_forChooserImageQuality.setItemText(1, _translate("widget_containSettingContent", "2"))
        self.comboBox_forChooserImageQuality.setItemText(2, _translate("widget_containSettingContent", "3"))
        self.comboBox_forChooserImageQuality.setItemText(3, _translate("widget_containSettingContent", "4"))
        self.comboBox_forChooserImageQuality.setItemText(4, _translate("widget_containSettingContent", "5"))
        self.comboBox_forChooserImageQuality.setItemText(5, _translate("widget_containSettingContent", "6"))
        self.comboBox_forChooseFaceMark.setItemText(0, _translate("widget_containSettingContent", "Có"))
        self.comboBox_forChooseFaceMark.setItemText(1, _translate("widget_containSettingContent", "Không"))
        self.label_coKhoanhKhuonMat.setText(_translate("widget_containSettingContent", "(Ảnh gửi lên có khung khoanh khuôn mặt)"))
        self.label_lamSachCamBien.setText(_translate("widget_containSettingContent", "Làm sạch cảm biến"))
        self.label_xoaBoRacCamBien.setText(_translate("widget_containSettingContent", "(Xóa các vân tay rác trên cảm biến)"))
        self.pushButton_cleanFGPsensor.setText(_translate("widget_containSettingContent", "Làm sạch"))
        self.label_tuDongTat_2.setText(_translate("widget_containSettingContent", "Tự động tắt"))
        self.label_ctTuDongTatvv_2.setText(_translate("widget_containSettingContent", "(Tự động tắt thiết bị sau thời gian không có người lái và không có người sử dụng )"))
        self.label_diaChi_6.setText(_translate("widget_containSettingContent", "Cổng mặc định"))
        self.label_diaChi_5.setText(_translate("widget_containSettingContent", "Mặt nạ "))
        self.label_diaChi_3.setText(_translate("widget_containSettingContent", "IP hiện tại"))
        self.label_ctThongTinCuavv_2.setText(_translate("widget_containSettingContent", "(Thông tin địa chỉ hiện tại của thiết bị)"))
        self.label_diaChi_7.setText(_translate("widget_containSettingContent", "Cài đặt IP thiết bị"))
        self.comboBox_choseIpMethod.setItemText(0, _translate("widget_containSettingContent", "Tự động"))
        self.comboBox_choseIpMethod.setItemText(1, _translate("widget_containSettingContent", "Thủ công"))
        self.pushButton_setManualIP.setText(_translate("widget_containSettingContent", "Cài đặt"))
        self.label_diaChi_8.setText(_translate("widget_containSettingContent", "Lấy IP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_containSettingContent = QtWidgets.QWidget()
    ui = Ui_widget_containSettingContent()
    ui.setupUi(widget_containSettingContent)
    widget_containSettingContent.show()
    sys.exit(app.exec_())
