# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoiDungCaiDatManHinh.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_containScreenSettingContent(object):
    def setupUi(self, widget_containScreenSettingContent):
        widget_containScreenSettingContent.setObjectName("widget_containScreenSettingContent")
        widget_containScreenSettingContent.resize(424, 700)
        self.frame_containBrightnessSetting = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.frame_containBrightnessSetting.setGeometry(QtCore.QRect(0, 186, 421, 91))
        self.frame_containBrightnessSetting.setStyleSheet("border: 0px;")
        self.frame_containBrightnessSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containBrightnessSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containBrightnessSetting.setObjectName("frame_containBrightnessSetting")
        self.label_doSangManHinh = QtWidgets.QLabel(self.frame_containBrightnessSetting)
        self.label_doSangManHinh.setGeometry(QtCore.QRect(10, 4, 385, 17))
        self.label_doSangManHinh.setMouseTracking(True)
        self.label_doSangManHinh.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_doSangManHinh.setObjectName("label_doSangManHinh")
        self.label_iconBrightness = QtWidgets.QLabel(self.frame_containBrightnessSetting)
        self.label_iconBrightness.setGeometry(QtCore.QRect(30, 56, 31, 31))
        self.label_iconBrightness.setText("")
        self.label_iconBrightness.setPixmap(QtGui.QPixmap("brightnessIcon.png"))
        self.label_iconBrightness.setObjectName("label_iconBrightness")
        self.horizontalSlider_forChangeBrightness = QtWidgets.QSlider(self.frame_containBrightnessSetting)
        self.horizontalSlider_forChangeBrightness.setGeometry(QtCore.QRect(80, 56, 251, 29))
        self.horizontalSlider_forChangeBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_forChangeBrightness.setObjectName("horizontalSlider_forChangeBrightness")
        self.label_2 = QtWidgets.QLabel(self.frame_containBrightnessSetting)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 385, 17))
        self.label_2.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_2.setObjectName("label_2")
        self.frame_containAutoScreenOffSetting = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.frame_containAutoScreenOffSetting.setGeometry(QtCore.QRect(0, 288, 421, 95))
        self.frame_containAutoScreenOffSetting.setStyleSheet("border: 0px;")
        self.frame_containAutoScreenOffSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containAutoScreenOffSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containAutoScreenOffSetting.setObjectName("frame_containAutoScreenOffSetting")
        self.label_tuDongTatManHinh = QtWidgets.QLabel(self.frame_containAutoScreenOffSetting)
        self.label_tuDongTatManHinh.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_tuDongTatManHinh.setMouseTracking(True)
        self.label_tuDongTatManHinh.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_tuDongTatManHinh.setWordWrap(True)
        self.label_tuDongTatManHinh.setObjectName("label_tuDongTatManHinh")
        self.label_ctTuDongTatvv = QtWidgets.QLabel(self.frame_containAutoScreenOffSetting)
        self.label_ctTuDongTatvv.setGeometry(QtCore.QRect(10, 34, 391, 21))
        self.label_ctTuDongTatvv.setMouseTracking(True)
        self.label_ctTuDongTatvv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctTuDongTatvv.setWordWrap(True)
        self.label_ctTuDongTatvv.setObjectName("label_ctTuDongTatvv")
        self.comboBox_forChooserTime = QtWidgets.QComboBox(self.frame_containAutoScreenOffSetting)
        self.comboBox_forChooserTime.setGeometry(QtCore.QRect(10, 62, 161, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_forChooserTime.setFont(font)
        self.comboBox_forChooserTime.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_forChooserTime.setObjectName("comboBox_forChooserTime")
        self.frame_containShowMapAllSetting = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.frame_containShowMapAllSetting.setGeometry(QtCore.QRect(0, 396, 421, 103))
        self.frame_containShowMapAllSetting.setStyleSheet("border: 0px;")
        self.frame_containShowMapAllSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containShowMapAllSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containShowMapAllSetting.setObjectName("frame_containShowMapAllSetting")
        self.label_tuDongHienThivv = QtWidgets.QLabel(self.frame_containShowMapAllSetting)
        self.label_tuDongHienThivv.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_tuDongHienThivv.setMouseTracking(True)
        self.label_tuDongHienThivv.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_tuDongHienThivv.setWordWrap(True)
        self.label_tuDongHienThivv.setObjectName("label_tuDongHienThivv")
        self.label_ctHienThiBanDovv = QtWidgets.QLabel(self.frame_containShowMapAllSetting)
        self.label_ctHienThiBanDovv.setGeometry(QtCore.QRect(10, 36, 391, 21))
        self.label_ctHienThiBanDovv.setMouseTracking(True)
        self.label_ctHienThiBanDovv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctHienThiBanDovv.setWordWrap(True)
        self.label_ctHienThiBanDovv.setObjectName("label_ctHienThiBanDovv")
        self.comboBox_forChooseTimeShowMap = QtWidgets.QComboBox(self.frame_containShowMapAllSetting)
        self.comboBox_forChooseTimeShowMap.setGeometry(QtCore.QRect(10, 64, 161, 31))
        self.comboBox_forChooseTimeShowMap.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);")
        self.comboBox_forChooseTimeShowMap.setObjectName("comboBox_forChooseTimeShowMap")
        self.frame_containChooseThemeSetting = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.frame_containChooseThemeSetting.setGeometry(QtCore.QRect(0, 514, 421, 181))
        self.frame_containChooseThemeSetting.setStyleSheet("border: 0px;")
        self.frame_containChooseThemeSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containChooseThemeSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containChooseThemeSetting.setObjectName("frame_containChooseThemeSetting")
        self.label_chuDe = QtWidgets.QLabel(self.frame_containChooseThemeSetting)
        self.label_chuDe.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_chuDe.setMouseTracking(True)
        self.label_chuDe.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_chuDe.setWordWrap(True)
        self.label_chuDe.setObjectName("label_chuDe")
        self.label_ctChuDeCuaPhanMem = QtWidgets.QLabel(self.frame_containChooseThemeSetting)
        self.label_ctChuDeCuaPhanMem.setGeometry(QtCore.QRect(10, 30, 391, 31))
        self.label_ctChuDeCuaPhanMem.setMouseTracking(True)
        self.label_ctChuDeCuaPhanMem.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctChuDeCuaPhanMem.setWordWrap(True)
        self.label_ctChuDeCuaPhanMem.setObjectName("label_ctChuDeCuaPhanMem")
        self.line_7 = QtWidgets.QFrame(self.frame_containChooseThemeSetting)
        self.line_7.setGeometry(QtCore.QRect(30, -20, 371, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.frame_containChooseThemeSetting)
        self.line_8.setGeometry(QtCore.QRect(40, -10, 371, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.frame_containLanguageSetting = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.frame_containLanguageSetting.setGeometry(QtCore.QRect(0, 58, 421, 111))
        self.frame_containLanguageSetting.setStyleSheet("border : 0px;")
        self.frame_containLanguageSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containLanguageSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containLanguageSetting.setObjectName("frame_containLanguageSetting")
        self.frame_chooseVIetNameseShadow = QtWidgets.QFrame(self.frame_containLanguageSetting)
        self.frame_chooseVIetNameseShadow.setGeometry(QtCore.QRect(10, 50, 81, 51))
        self.frame_chooseVIetNameseShadow.setStyleSheet("")
        self.frame_chooseVIetNameseShadow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chooseVIetNameseShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chooseVIetNameseShadow.setObjectName("frame_chooseVIetNameseShadow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_chooseVIetNameseShadow)
        self.verticalLayout.setContentsMargins(-1, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_vietNameseIcon = QtWidgets.QLabel(self.frame_chooseVIetNameseShadow)
        self.label_vietNameseIcon.setText("")
        self.label_vietNameseIcon.setPixmap(QtGui.QPixmap("iconVietNamese.png"))
        self.label_vietNameseIcon.setObjectName("label_vietNameseIcon")
        self.verticalLayout.addWidget(self.label_vietNameseIcon)
        self.frame_chooseEnglishShadow = QtWidgets.QFrame(self.frame_containLanguageSetting)
        self.frame_chooseEnglishShadow.setGeometry(QtCore.QRect(100, 50, 81, 51))
        self.frame_chooseEnglishShadow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_chooseEnglishShadow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_chooseEnglishShadow.setObjectName("frame_chooseEnglishShadow")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_chooseEnglishShadow)
        self.verticalLayout_2.setContentsMargins(-1, 4, 4, 4)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_englishIcon = QtWidgets.QLabel(self.frame_chooseEnglishShadow)
        self.label_englishIcon.setText("")
        self.label_englishIcon.setPixmap(QtGui.QPixmap("iconEnglish.png"))
        self.label_englishIcon.setObjectName("label_englishIcon")
        self.verticalLayout_2.addWidget(self.label_englishIcon)
        self.label_ngonNgu = QtWidgets.QLabel(self.frame_containLanguageSetting)
        self.label_ngonNgu.setGeometry(QtCore.QRect(12, 6, 161, 17))
        self.label_ngonNgu.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_ngonNgu.setObjectName("label_ngonNgu")
        self.label_ctNgonNguCuaVV = QtWidgets.QLabel(self.frame_containLanguageSetting)
        self.label_ctNgonNguCuaVV.setGeometry(QtCore.QRect(12, 30, 311, 17))
        self.label_ctNgonNguCuaVV.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctNgonNguCuaVV.setObjectName("label_ctNgonNguCuaVV")
        self.label = QtWidgets.QLabel(widget_containScreenSettingContent)
        self.label.setGeometry(QtCore.QRect(160, 0, 153, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("font: 75 bold 18pt \"Ubuntu\";\n"
"color: rgb(85, 85, 0);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.line_3.setGeometry(QtCore.QRect(30, 40, 371, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.line_4.setGeometry(QtCore.QRect(30, 168, 371, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.line_5.setGeometry(QtCore.QRect(30, 274, 371, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.line_6.setGeometry(QtCore.QRect(30, 380, 371, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_9 = QtWidgets.QFrame(widget_containScreenSettingContent)
        self.line_9.setGeometry(QtCore.QRect(30, 498, 371, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.retranslateUi(widget_containScreenSettingContent)
        QtCore.QMetaObject.connectSlotsByName(widget_containScreenSettingContent)

    def retranslateUi(self, widget_containScreenSettingContent):
        _translate = QtCore.QCoreApplication.translate
        widget_containScreenSettingContent.setWindowTitle(_translate("widget_containScreenSettingContent", "Form"))
        self.label_doSangManHinh.setText(_translate("widget_containScreenSettingContent", "Độ sáng của màn hình"))
        self.label_2.setText(_translate("widget_containScreenSettingContent", "Độ sáng màn hình của thiết bị"))
        self.label_tuDongTatManHinh.setText(_translate("widget_containScreenSettingContent", "Tự động tắt màn hình"))
        self.label_ctTuDongTatvv.setText(_translate("widget_containScreenSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Tự động tắt màn hình sau thời gian không có người lái)</span></p></body></html>"))
        self.label_tuDongHienThivv.setText(_translate("widget_containScreenSettingContent", "Tự động hiển thị toàn màn hình"))
        self.label_ctHienThiBanDovv.setText(_translate("widget_containScreenSettingContent", "(Hiển thị bản đồ toàn màn hình sau một thời gian không thao tác)"))
        self.label_chuDe.setText(_translate("widget_containScreenSettingContent", "Chủ đề"))
        self.label_ctChuDeCuaPhanMem.setText(_translate("widget_containScreenSettingContent", "(Chủ đề của giao diện)"))
        self.label_ngonNgu.setText(_translate("widget_containScreenSettingContent", "Ngôn ngữ"))
        self.label_ctNgonNguCuaVV.setText(_translate("widget_containScreenSettingContent", "(Ngôn ngữ của thiết bị)"))
        self.label.setText(_translate("widget_containScreenSettingContent", "HIỂN THỊ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_containScreenSettingContent = QtWidgets.QWidget()
    ui = Ui_widget_containScreenSettingContent()
    ui.setupUi(widget_containScreenSettingContent)
    widget_containScreenSettingContent.show()
    sys.exit(app.exec_())
