from SettingScreen.ScreenSettingContentUI import Ui_widget_containScreenSettingContent
from PyQt5.QtCore import pyqtSlot, pyqtSignal,QTimer, QDateTime, Qt, QObject, QPointF, QPropertyAnimation, pyqtProperty
from PyQt5 import QtWidgets

class ScreenSettingContent(Ui_widget_containScreenSettingContent, QObject):
    ChangeLanguageEvent = pyqtSignal(str)
    ChangeBrightnessEvent = pyqtSignal(int)
    ChangeTimeScreenOffEvent = pyqtSignal(str)
    ChangeTimeShowAllMapEvent = pyqtSignal(str)
    def __init__(self):
        QObject.__init__(self)
        Ui_widget_containScreenSettingContent.__init__(self)
        self.scrollAreaContent = QtWidgets.QWidget()
        self.setupUi(self.scrollAreaContent)
        self.comboBox_forChooserTime.addItems(("1 Phút", "2 Phút", "5 Phút", "15 Phút", "30 Phút", "1 Giờ"))
        self.comboBox_forChooseTimeShowMap.addItems(("30 giây", "1 Phút", "2 Phút", "5 Phút", "15 Phút", "30 Phút", "1 Giờ" ))
        self.label_vietNameseIcon.enterEvent = lambda event: self.ChooseLanguageMouseEnter(1)
        self.label_englishIcon.enterEvent = lambda event: self.ChooseLanguageMouseEnter(2)
        self.label_vietNameseIcon.setPixmap(QtGui.QPixmap("icon/iconVietNamese.png"))
        self.label_englishIcon.setPixmap(QtGui.QPixmap("icon/iconEnglish.png"))
        self.label_iconBrightness.setPixmap(QtGui.QPixmap("icon/brightnessIcon.png"))
    def ChooseLanguageMouseEnter(self, sender):
        pass
    
    def SaveSetting(self):
        pass

    def GetWidgetContent(self):
        return self.scrollAreaContent
    # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoiDungManHinhCaiDatHeThong.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_containSettingContent(object):
    def setupUi(self, widget_containSettingContent):
        widget_containSettingContent.setObjectName("widget_containSettingContent")
        widget_containSettingContent.resize(421, 1148)
        self.frame_autoShutdown = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_autoShutdown.setGeometry(QtCore.QRect(0, 70, 421, 111))
        self.frame_autoShutdown.setStyleSheet("border: 0px")
        self.frame_autoShutdown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_autoShutdown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_autoShutdown.setObjectName("frame_autoShutdown")
        self.label_tuDongTat = QtWidgets.QLabel(self.frame_autoShutdown)
        self.label_tuDongTat.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_tuDongTat.setWordWrap(True)
        self.label_tuDongTat.setObjectName("label_tuDongTat")
        self.label_ctTuDongTatvv = QtWidgets.QLabel(self.frame_autoShutdown)
        self.label_ctTuDongTatvv.setGeometry(QtCore.QRect(10, 30, 391, 41))
        self.label_ctTuDongTatvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctTuDongTatvv.setWordWrap(True)
        self.label_ctTuDongTatvv.setObjectName("label_ctTuDongTatvv")
        self.comboBox_chooseTime = QtWidgets.QComboBox(self.frame_autoShutdown)
        self.comboBox_chooseTime.setGeometry(QtCore.QRect(10, 70, 151, 27))
        self.comboBox_chooseTime.setStyleSheet("")
        self.comboBox_chooseTime.setObjectName("comboBox_chooseTime")
        self.line = QtWidgets.QFrame(self.frame_autoShutdown)
        self.line.setGeometry(QtCore.QRect(30, 0, 118, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_autoShutdown)
        self.line_2.setGeometry(QtCore.QRect(20, -10, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame_serverInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_serverInfomation.setGeometry(QtCore.QRect(0, 190, 421, 181))
        self.frame_serverInfomation.setStyleSheet("border: 0px")
        self.frame_serverInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_serverInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_serverInfomation.setObjectName("frame_serverInfomation")
        self.label_thongTinMayChu = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_thongTinMayChu.setGeometry(QtCore.QRect(10, 10, 371, 21))
        self.label_thongTinMayChu.setWordWrap(True)
        self.label_thongTinMayChu.setObjectName("label_thongTinMayChu")
        self.label_ctThongTinCuavv = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_ctThongTinCuavv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctThongTinCuavv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctThongTinCuavv.setWordWrap(True)
        self.label_ctThongTinCuavv.setObjectName("label_ctThongTinCuavv")
        self.label_diaChi = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_diaChi.setGeometry(QtCore.QRect(40, 60, 81, 17))
        self.label_diaChi.setObjectName("label_diaChi")
        self.lineEdit_forInputIP = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputIP.setGeometry(QtCore.QRect(130, 60, 221, 27))
        self.lineEdit_forInputIP.setObjectName("lineEdit_forInputIP")
        self.label_cong = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_cong.setGeometry(QtCore.QRect(40, 90, 81, 17))
        self.label_cong.setObjectName("label_cong")
        self.lineEdit_forInputPort = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputPort.setGeometry(QtCore.QRect(130, 90, 221, 27))
        self.lineEdit_forInputPort.setObjectName("lineEdit_forInputPort")
        self.lineEdit_forInputAccount = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputAccount.setGeometry(QtCore.QRect(130, 120, 221, 27))
        self.lineEdit_forInputAccount.setObjectName("lineEdit_forInputAccount")
        self.label_taiKhoan = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_taiKhoan.setGeometry(QtCore.QRect(40, 120, 81, 17))
        self.label_taiKhoan.setObjectName("label_taiKhoan")
        self.lineEdit_forInputPassword = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputPassword.setGeometry(QtCore.QRect(130, 150, 221, 27))
        self.lineEdit_forInputPassword.setObjectName("lineEdit_forInputPassword")
        self.label_matKhau = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_matKhau.setGeometry(QtCore.QRect(40, 150, 81, 17))
        self.label_matKhau.setObjectName("label_matKhau")
        self.frame_containFTPserverInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFTPserverInfomation.setGeometry(QtCore.QRect(0, 380, 421, 181))
        self.frame_containFTPserverInfomation.setStyleSheet("border: 0px")
        self.frame_containFTPserverInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFTPserverInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFTPserverInfomation.setObjectName("frame_containFTPserverInfomation")
        self.label_thongTinMayChuDuLieu = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_thongTinMayChuDuLieu.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_thongTinMayChuDuLieu.setWordWrap(True)
        self.label_thongTinMayChuDuLieu.setObjectName("label_thongTinMayChuDuLieu")
        self.label_ctThongTinMayvv = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_ctThongTinMayvv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctThongTinMayvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctThongTinMayvv.setWordWrap(True)
        self.label_ctThongTinMayvv.setObjectName("label_ctThongTinMayvv")
        self.label_diaChiIPFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_diaChiIPFTP.setGeometry(QtCore.QRect(40, 60, 81, 17))
        self.label_diaChiIPFTP.setObjectName("label_diaChiIPFTP")
        self.lineEdit_forInputFTPIP = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPIP.setGeometry(QtCore.QRect(130, 60, 221, 27))
        self.lineEdit_forInputFTPIP.setObjectName("lineEdit_forInputFTPIP")
        self.label_congFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_congFTP.setGeometry(QtCore.QRect(40, 90, 81, 17))
        self.label_congFTP.setObjectName("label_congFTP")
        self.lineEdit_forInputFTPport = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPport.setGeometry(QtCore.QRect(130, 90, 221, 27))
        self.lineEdit_forInputFTPport.setObjectName("lineEdit_forInputFTPport")
        self.lineEdit_forInputFTPaccount = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFTPaccount.setGeometry(QtCore.QRect(130, 120, 221, 27))
        self.lineEdit_forInputFTPaccount.setObjectName("lineEdit_forInputFTPaccount")
        self.label_taiKhoanFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_taiKhoanFTP.setGeometry(QtCore.QRect(40, 120, 81, 17))
        self.label_taiKhoanFTP.setObjectName("label_taiKhoanFTP")
        self.lineEdit_forInputFPTpassword = QtWidgets.QLineEdit(self.frame_containFTPserverInfomation)
        self.lineEdit_forInputFPTpassword.setGeometry(QtCore.QRect(130, 150, 221, 27))
        self.lineEdit_forInputFPTpassword.setObjectName("lineEdit_forInputFPTpassword")
        self.label_matKhauFTP = QtWidgets.QLabel(self.frame_containFTPserverInfomation)
        self.label_matKhauFTP.setGeometry(QtCore.QRect(40, 150, 81, 17))
        self.label_matKhauFTP.setObjectName("label_matKhauFTP")
        self.frame_containActivationHistory = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containActivationHistory.setGeometry(QtCore.QRect(0, 570, 421, 151))
        self.frame_containActivationHistory.setStyleSheet("border: 0px")
        self.frame_containActivationHistory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containActivationHistory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containActivationHistory.setObjectName("frame_containActivationHistory")
        self.label_thongKeThoiGian = QtWidgets.QLabel(self.frame_containActivationHistory)
        self.label_thongKeThoiGian.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_thongKeThoiGian.setWordWrap(True)
        self.label_thongKeThoiGian.setObjectName("label_thongKeThoiGian")
        self.label_ctThongKeLichvv = QtWidgets.QLabel(self.frame_containActivationHistory)
        self.label_ctThongKeLichvv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctThongKeLichvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctThongKeLichvv.setWordWrap(True)
        self.label_ctThongKeLichvv.setObjectName("label_ctThongKeLichvv")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_containActivationHistory)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 60, 373, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_containActivationHistory = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_containActivationHistory.setContentsMargins(0, 0, 0, 0)
        self.formLayout_containActivationHistory.setSpacing(10)
        self.formLayout_containActivationHistory.setObjectName("formLayout_containActivationHistory")
        self.label_ngayDangKy = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_ngayDangKy.setObjectName("label_ngayDangKy")
        self.formLayout_containActivationHistory.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_ngayDangKy)
        self.label_soKMdaChay = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_soKMdaChay.setObjectName("label_soKMdaChay")
        self.formLayout_containActivationHistory.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_soKMdaChay)
        self.label_tongThoiGianHoatDong = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_tongThoiGianHoatDong.setObjectName("label_tongThoiGianHoatDong")
        self.formLayout_containActivationHistory.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_tongThoiGianHoatDong)
        self.label_forShowRegistTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_forShowRegistTime.setObjectName("label_forShowRegistTime")
        self.formLayout_containActivationHistory.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_forShowRegistTime)
        self.label_forShowKMhasGone = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_forShowKMhasGone.setObjectName("label_forShowKMhasGone")
        self.formLayout_containActivationHistory.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_forShowKMhasGone)
        self.label_forShowActiveTime = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_forShowActiveTime.setObjectName("label_forShowActiveTime")
        self.formLayout_containActivationHistory.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_forShowActiveTime)
        self.frame_containMemoryInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containMemoryInfomation.setGeometry(QtCore.QRect(0, 730, 421, 141))
        self.frame_containMemoryInfomation.setStyleSheet("border: 0px")
        self.frame_containMemoryInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containMemoryInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containMemoryInfomation.setObjectName("frame_containMemoryInfomation")
        self.label_thongTinBoNho = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_thongTinBoNho.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_thongTinBoNho.setWordWrap(True)
        self.label_thongTinBoNho.setObjectName("label_thongTinBoNho")
        self.label_ctBoNhoSuvv = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_ctBoNhoSuvv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctBoNhoSuvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctBoNhoSuvv.setWordWrap(True)
        self.label_ctBoNhoSuvv.setObjectName("label_ctBoNhoSuvv")
        self.tableView_forShowMemoryInformation = QtWidgets.QTableView(self.frame_containMemoryInfomation)
        self.tableView_forShowMemoryInformation.setGeometry(QtCore.QRect(10, 50, 401, 81))
        self.tableView_forShowMemoryInformation.setObjectName("tableView_forShowMemoryInformation")
        self.frame_containFirmwareInformation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFirmwareInformation.setGeometry(QtCore.QRect(0, 880, 421, 191))
        self.frame_containFirmwareInformation.setStyleSheet("border: 0px")
        self.frame_containFirmwareInformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFirmwareInformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFirmwareInformation.setObjectName("frame_containFirmwareInformation")
        self.label_phienBanPhanMem = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_phienBanPhanMem.setGeometry(QtCore.QRect(10, 10, 391, 21))
        self.label_phienBanPhanMem.setWordWrap(True)
        self.label_phienBanPhanMem.setObjectName("label_phienBanPhanMem")
        self.label_ctPHanMemTrenvv = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_ctPHanMemTrenvv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctPHanMemTrenvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctPHanMemTrenvv.setWordWrap(True)
        self.label_ctPHanMemTrenvv.setObjectName("label_ctPHanMemTrenvv")
        self.label_phienBan = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_phienBan.setGeometry(QtCore.QRect(40, 60, 81, 17))
        self.label_phienBan.setObjectName("label_phienBan")
        self.label_forShowFirmwareVersion = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_forShowFirmwareVersion.setGeometry(QtCore.QRect(180, 60, 131, 17))
        self.label_forShowFirmwareVersion.setObjectName("label_forShowFirmwareVersion")
        self.label_forShowUpdateTime = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_forShowUpdateTime.setGeometry(QtCore.QRect(180, 90, 161, 17))
        self.label_forShowUpdateTime.setObjectName("label_forShowUpdateTime")
        self.label_ngayGioCapNhat = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_ngayGioCapNhat.setGeometry(QtCore.QRect(40, 90, 141, 17))
        self.label_ngayGioCapNhat.setObjectName("label_ngayGioCapNhat")
        self.label_banQuyen = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_banQuyen.setGeometry(QtCore.QRect(40, 120, 111, 17))
        self.label_banQuyen.setObjectName("label_banQuyen")
        self.label_forShowCopyright = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_forShowCopyright.setGeometry(QtCore.QRect(180, 120, 221, 31))
        self.label_forShowCopyright.setWordWrap(True)
        self.label_forShowCopyright.setObjectName("label_forShowCopyright")
        self.pushButton_checkUpdate = QtWidgets.QPushButton(self.frame_containFirmwareInformation)
        self.pushButton_checkUpdate.setGeometry(QtCore.QRect(40, 160, 141, 27))
        self.pushButton_checkUpdate.setObjectName("pushButton_checkUpdate")
        self.line_3 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_3.setGeometry(QtCore.QRect(20, 60, 371, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_4.setGeometry(QtCore.QRect(20, 240, 371, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_5.setGeometry(QtCore.QRect(20, 370, 371, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_6.setGeometry(QtCore.QRect(20, 560, 371, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_7.setGeometry(QtCore.QRect(20, 780, 371, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_8.setGeometry(QtCore.QRect(30, 920, 371, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label = QtWidgets.QLabel(widget_containSettingContent)
        self.label.setGeometry(QtCore.QRect(170, 10, 131, 51))
        self.label.setObjectName("label")
        self.frame_autoShutdown.raise_()
        self.frame_serverInfomation.raise_()
        self.frame_containFTPserverInfomation.raise_()
        self.frame_containActivationHistory.raise_()
        self.frame_containMemoryInfomation.raise_()
        self.frame_containFirmwareInformation.raise_()
        self.line_8.raise_()
        self.line_3.raise_()
        self.line_6.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_7.raise_()
        self.label.raise_()

        self.retranslateUi(widget_containSettingContent)
        QtCore.QMetaObject.connectSlotsByName(widget_containSettingContent)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputPassword, self.lineEdit_forInputFTPIP)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPIP, self.lineEdit_forInputFTPport)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPport, self.lineEdit_forInputAccount)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputAccount, self.lineEdit_forInputIP)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputIP, self.lineEdit_forInputPort)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputPort, self.lineEdit_forInputFTPaccount)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFTPaccount, self.lineEdit_forInputFPTpassword)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputFPTpassword, self.tableView_forShowMemoryInformation)
        widget_containSettingContent.setTabOrder(self.tableView_forShowMemoryInformation, self.comboBox_chooseTime)
        widget_containSettingContent.setTabOrder(self.comboBox_chooseTime, self.pushButton_checkUpdate)

    def retranslateUi(self, widget_containSettingContent):
        _translate = QtCore.QCoreApplication.translate
        widget_containSettingContent.setWindowTitle(_translate("widget_containSettingContent", "Form"))
        self.label_tuDongTat.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:12pt;\">Tự động tắt</span></p></body></html>"))
        self.label_ctTuDongTatvv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Tự động tắt thiết bị sau thời gian không có người lái và không có người sử dụng )</span></p></body></html>"))
        self.label_thongTinMayChu.setText(_translate("widget_containSettingContent", "<html><head/><body><p>Thông tin máy chủ</p></body></html>"))
        self.label_ctThongTinCuavv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Thông tin của máy chủ trung tâm điều khiển thiết bị) </span></p></body></html>"))
        self.label_diaChi.setText(_translate("widget_containSettingContent", "Địa chỉ IP"))
        self.label_cong.setText(_translate("widget_containSettingContent", "Cổng"))
        self.label_taiKhoan.setText(_translate("widget_containSettingContent", "Tài khoản"))
        self.label_matKhau.setText(_translate("widget_containSettingContent", "Mật khẩu"))
        self.label_thongTinMayChuDuLieu.setText(_translate("widget_containSettingContent", "<html><head/><body><p>Thông tin máy chủ dữ liệu</p></body></html>"))
        self.label_ctThongTinMayvv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Thông tin của máy chủ FTP) </span></p></body></html>"))
        self.label_diaChiIPFTP.setText(_translate("widget_containSettingContent", "Địa chỉ IP"))
        self.label_congFTP.setText(_translate("widget_containSettingContent", "Cổng"))
        self.label_taiKhoanFTP.setText(_translate("widget_containSettingContent", "Tài khoản"))
        self.label_matKhauFTP.setText(_translate("widget_containSettingContent", "Mật khẩu"))
        self.label_thongKeThoiGian.setText(_translate("widget_containSettingContent", "<html><head/><body><p>Thống kê hoạt động</p></body></html>"))
        self.label_ctThongKeLichvv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Thống kê lịch sử hoạt động của thiết bị)</span></p></body></html>"))
        self.label_ngayDangKy.setText(_translate("widget_containSettingContent", "Ngày đăng ký"))
        self.label_soKMdaChay.setText(_translate("widget_containSettingContent", "Tổng số KM đã chạy"))
        self.label_tongThoiGianHoatDong.setText(_translate("widget_containSettingContent", "Tổng thời gian hoạt động"))
        self.label_forShowRegistTime.setText(_translate("widget_containSettingContent", "Chưa đăng ký"))
        self.label_forShowKMhasGone.setText(_translate("widget_containSettingContent", "Chưa chạy"))
        self.label_forShowActiveTime.setText(_translate("widget_containSettingContent", "Chưa chạy"))
        self.label_thongTinBoNho.setText(_translate("widget_containSettingContent", "<html><head/><body><p>Thông tin bộ nhớ</p></body></html>"))
        self.label_ctBoNhoSuvv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Bộ nhớ sử dụng trên thiết bị)</span></p></body></html>"))
        self.label_phienBanPhanMem.setText(_translate("widget_containSettingContent", "<html><head/><body><p>Phiên bản phần mềm</p></body></html>"))
        self.label_ctPHanMemTrenvv.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:10pt;\">(Phần mềm của thiết bị)</span></p></body></html>"))
        self.label_phienBan.setText(_translate("widget_containSettingContent", "Phiên bản:"))
        self.label_forShowFirmwareVersion.setText(_translate("widget_containSettingContent", "1.0.0"))
        self.label_forShowUpdateTime.setText(_translate("widget_containSettingContent", "30/10/2019 - 18:24:00"))
        self.label_ngayGioCapNhat.setText(_translate("widget_containSettingContent", "Cập nhật ngày, giờ:"))
        self.label_banQuyen.setText(_translate("widget_containSettingContent", "Bản quyền:"))
        self.label_forShowCopyright.setText(_translate("widget_containSettingContent", "Công ty cổ phần công nghệ và kỹ thuật Ecotek"))
        self.pushButton_checkUpdate.setText(_translate("widget_containSettingContent", "Kiểm tra cập nhật"))
        self.label.setText(_translate("widget_containSettingContent", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#6f6f53;\">HỆ THỐNG</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_containSettingContent = QtWidgets.QWidget()
    ui = Ui_widget_containSettingContent()
    ui.setupUi(widget_containSettingContent)
    widget_containSettingContent.show()
    sys.exit(app.exec_())
