# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoiDungManHinhCaiDatHeThong.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_containSettingContent(object):
    def setupUi(self, widget_containSettingContent):
        widget_containSettingContent.setObjectName("widget_containSettingContent")
        widget_containSettingContent.resize(416, 1027)
        self.frame_serverInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_serverInfomation.setGeometry(QtCore.QRect(0, 300, 421, 261))
        self.frame_serverInfomation.setStyleSheet("border: 0px")
        self.frame_serverInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_serverInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_serverInfomation.setObjectName("frame_serverInfomation")
        self.label_ctThongTinCuavv = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_ctThongTinCuavv.setGeometry(QtCore.QRect(10, 30, 391, 21))
        self.label_ctThongTinCuavv.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctThongTinCuavv.setWordWrap(True)
        self.label_ctThongTinCuavv.setObjectName("label_ctThongTinCuavv")
        self.label_diaChi = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_diaChi.setGeometry(QtCore.QRect(40, 60, 81, 17))
        self.label_diaChi.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi.setObjectName("label_diaChi")
        self.lineEdit_forInputIP = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputIP.setGeometry(QtCore.QRect(130, 50, 221, 30))
        self.lineEdit_forInputIP.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputIP.setObjectName("lineEdit_forInputIP")
        self.label_cong = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_cong.setGeometry(QtCore.QRect(40, 100, 81, 17))
        self.label_cong.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_cong.setObjectName("label_cong")
        self.lineEdit_forInputPort = QtWidgets.QLineEdit(self.frame_serverInfomation)
        self.lineEdit_forInputPort.setGeometry(QtCore.QRect(130, 90, 221, 30))
        self.lineEdit_forInputPort.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.lineEdit_forInputPort.setObjectName("lineEdit_forInputPort")
        self.label_diaChi_2 = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_diaChi_2.setGeometry(QtCore.QRect(10, 6, 241, 16))
        self.label_diaChi_2.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_diaChi_2.setObjectName("label_diaChi_2")
        self.label_iconCheckServerIP = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerIP.setGeometry(QtCore.QRect(368, 50, 23, 29))
        self.label_iconCheckServerIP.setText("")
        self.label_iconCheckServerIP.setPixmap(QtGui.QPixmap("../../../../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerIP.setObjectName("label_iconCheckServerIP")
        self.label_iconCheckServerPort = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerPort.setGeometry(QtCore.QRect(368, 90, 25, 25))
        self.label_iconCheckServerPort.setText("")
        self.label_iconCheckServerPort.setPixmap(QtGui.QPixmap("../../../../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerPort.setObjectName("label_iconCheckServerPort")
        self.label_iconCheckServerAccount = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerAccount.setGeometry(QtCore.QRect(368, 130, 25, 25))
        self.label_iconCheckServerAccount.setText("")
        self.label_iconCheckServerAccount.setPixmap(QtGui.QPixmap("../../../../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerAccount.setObjectName("label_iconCheckServerAccount")
        self.label_iconCheckServerPassword = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconCheckServerPassword.setGeometry(QtCore.QRect(368, 170, 25, 25))
        self.label_iconCheckServerPassword.setText("")
        self.label_iconCheckServerPassword.setPixmap(QtGui.QPixmap("../../../../../../../../icon/iconCheckFail.png"))
        self.label_iconCheckServerPassword.setObjectName("label_iconCheckServerPassword")
        self.pushButton_connectNewServer = QtWidgets.QPushButton(self.frame_serverInfomation)
        self.pushButton_connectNewServer.setGeometry(QtCore.QRect(300, 170, 101, 41))
        self.pushButton_connectNewServer.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../Downloads/iconConnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_connectNewServer.setIcon(icon)
        self.pushButton_connectNewServer.setObjectName("pushButton_connectNewServer")
        self.label_showSocketConnectStatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_showSocketConnectStatus.setGeometry(QtCore.QRect(60, 130, 231, 51))
        self.label_showSocketConnectStatus.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_showSocketConnectStatus.setText("")
        self.label_showSocketConnectStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_showSocketConnectStatus.setWordWrap(True)
        self.label_showSocketConnectStatus.setObjectName("label_showSocketConnectStatus")
        self.label_iconSocketStatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_iconSocketStatus.setGeometry(QtCore.QRect(8, 130, 39, 37))
        self.label_iconSocketStatus.setText("")
        self.label_iconSocketStatus.setObjectName("label_iconSocketStatus")
        self.label_forShowIconFTPstatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_forShowIconFTPstatus.setGeometry(QtCore.QRect(10, 190, 39, 37))
        self.label_forShowIconFTPstatus.setText("")
        self.label_forShowIconFTPstatus.setObjectName("label_forShowIconFTPstatus")
        self.label_showFTPconnectStatus = QtWidgets.QLabel(self.frame_serverInfomation)
        self.label_showFTPconnectStatus.setGeometry(QtCore.QRect(60, 180, 231, 61))
        self.label_showFTPconnectStatus.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_showFTPconnectStatus.setText("")
        self.label_showFTPconnectStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_showFTPconnectStatus.setWordWrap(True)
        self.label_showFTPconnectStatus.setObjectName("label_showFTPconnectStatus")
        self.frame_containMemoryInfomation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containMemoryInfomation.setGeometry(QtCore.QRect(0, 580, 421, 149))
        self.frame_containMemoryInfomation.setStyleSheet("border: 0px")
        self.frame_containMemoryInfomation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containMemoryInfomation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containMemoryInfomation.setObjectName("frame_containMemoryInfomation")
        self.label_thongTinBoNho = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_thongTinBoNho.setGeometry(QtCore.QRect(10, 12, 391, 21))
        self.label_thongTinBoNho.setMouseTracking(True)
        self.label_thongTinBoNho.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_thongTinBoNho.setWordWrap(True)
        self.label_thongTinBoNho.setObjectName("label_thongTinBoNho")
        self.label_ctBoNhoSuvv = QtWidgets.QLabel(self.frame_containMemoryInfomation)
        self.label_ctBoNhoSuvv.setGeometry(QtCore.QRect(10, 34, 391, 21))
        self.label_ctBoNhoSuvv.setMouseTracking(True)
        self.label_ctBoNhoSuvv.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctBoNhoSuvv.setWordWrap(True)
        self.label_ctBoNhoSuvv.setObjectName("label_ctBoNhoSuvv")
        self.pushButton_deleteAllData = QtWidgets.QPushButton(self.frame_containMemoryInfomation)
        self.pushButton_deleteAllData.setGeometry(QtCore.QRect(22, 66, 65, 31))
        self.pushButton_deleteAllData.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_deleteAllData.setObjectName("pushButton_deleteAllData")
        self.frame_containFirmwareInformation = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_containFirmwareInformation.setGeometry(QtCore.QRect(10, 750, 421, 265))
        self.frame_containFirmwareInformation.setStyleSheet("border: 0px")
        self.frame_containFirmwareInformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_containFirmwareInformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_containFirmwareInformation.setObjectName("frame_containFirmwareInformation")
        self.label_phienBanPhanMem = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_phienBanPhanMem.setGeometry(QtCore.QRect(10, 12, 391, 21))
        self.label_phienBanPhanMem.setMouseTracking(True)
        self.label_phienBanPhanMem.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);")
        self.label_phienBanPhanMem.setWordWrap(True)
        self.label_phienBanPhanMem.setObjectName("label_phienBanPhanMem")
        self.label_ctPHanMemTrenvv = QtWidgets.QLabel(self.frame_containFirmwareInformation)
        self.label_ctPHanMemTrenvv.setGeometry(QtCore.QRect(10, 38, 391, 25))
        self.label_ctPHanMemTrenvv.setMouseTracking(True)
        self.label_ctPHanMemTrenvv.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_ctPHanMemTrenvv.setWordWrap(True)
        self.label_ctPHanMemTrenvv.setObjectName("label_ctPHanMemTrenvv")
        self.pushButton_checkUpdate = QtWidgets.QPushButton(self.frame_containFirmwareInformation)
        self.pushButton_checkUpdate.setGeometry(QtCore.QRect(20, 178, 151, 59))
        self.pushButton_checkUpdate.setStyleSheet("margin: 1px; padding: 7px;\n"
"background-color: rgb(214, 214, 160);\n"
"color: rgba(0,190,255,255);\n"
"border-style: solid;\n"
"border-radius: 3px;\n"
"border-width: 1px;\n"
"border-color: rgba(0,140,255,255);\n"
"")
        self.pushButton_checkUpdate.setObjectName("pushButton_checkUpdate")
        self.layoutWidget = QtWidgets.QWidget(self.frame_containFirmwareInformation)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 82, 134, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_phienBan = QtWidgets.QLabel(self.layoutWidget)
        self.label_phienBan.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_phienBan.setObjectName("label_phienBan")
        self.verticalLayout.addWidget(self.label_phienBan)
        self.label_ngayGioCapNhat = QtWidgets.QLabel(self.layoutWidget)
        self.label_ngayGioCapNhat.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_ngayGioCapNhat.setObjectName("label_ngayGioCapNhat")
        self.verticalLayout.addWidget(self.label_ngayGioCapNhat)
        self.label_banQuyen = QtWidgets.QLabel(self.layoutWidget)
        self.label_banQuyen.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_banQuyen.setObjectName("label_banQuyen")
        self.verticalLayout.addWidget(self.label_banQuyen)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_containFirmwareInformation)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 80, 171, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_forShowFirmwareVersion = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowFirmwareVersion.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_forShowFirmwareVersion.setObjectName("label_forShowFirmwareVersion")
        self.verticalLayout_2.addWidget(self.label_forShowFirmwareVersion)
        self.label_forShowUpdateTime = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowUpdateTime.setText("")
        self.label_forShowUpdateTime.setObjectName("label_forShowUpdateTime")
        self.verticalLayout_2.addWidget(self.label_forShowUpdateTime)
        self.label_forShowCopyright = QtWidgets.QLabel(self.layoutWidget1)
        self.label_forShowCopyright.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_forShowCopyright.setWordWrap(True)
        self.label_forShowCopyright.setObjectName("label_forShowCopyright")
        self.verticalLayout_2.addWidget(self.label_forShowCopyright)
        self.line_3 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_3.setGeometry(QtCore.QRect(20, 50, 371, 1))
        self.line_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_4.setGeometry(QtCore.QRect(20, 300, 371, 1))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(widget_containSettingContent)
        self.label.setGeometry(QtCore.QRect(148, 10, 189, 39))
        self.label.setMouseTracking(True)
        self.label.setStyleSheet("font: 75 bold 18pt \"Ubuntu\";\n"
"color: rgb(85, 85, 0);")
        self.label.setObjectName("label")
        self.line_11 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_11.setGeometry(QtCore.QRect(20, 740, 371, 1))
        self.line_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_12.setGeometry(QtCore.QRect(24, 570, 371, 1))
        self.line_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_6 = QtWidgets.QFrame(widget_containSettingContent)
        self.line_6.setGeometry(QtCore.QRect(20, 1020, 371, 1))
        self.line_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_diaChi_4 = QtWidgets.QLabel(widget_containSettingContent)
        self.label_diaChi_4.setGeometry(QtCore.QRect(30, 110, 81, 17))
        self.label_diaChi_4.setText("")
        self.label_diaChi_4.setObjectName("label_diaChi_4")
        self.frame_autoShutdown_2 = QtWidgets.QFrame(widget_containSettingContent)
        self.frame_autoShutdown_2.setGeometry(QtCore.QRect(0, 60, 421, 231))
        self.frame_autoShutdown_2.setStyleSheet("border: 0px")
        self.frame_autoShutdown_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_autoShutdown_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_autoShutdown_2.setObjectName("frame_autoShutdown_2")
        self.label_gateway = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_gateway.setGeometry(QtCore.QRect(160, 130, 221, 27))
        self.label_gateway.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_gateway.setText("")
        self.label_gateway.setObjectName("label_gateway")
        self.label_diaChi_6 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_6.setGeometry(QtCore.QRect(30, 139, 121, 21))
        self.label_diaChi_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_6.setObjectName("label_diaChi_6")
        self.label_diaChi_5 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_5.setGeometry(QtCore.QRect(30, 110, 111, 20))
        self.label_diaChi_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_5.setObjectName("label_diaChi_5")
        self.label_subnetMask = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_subnetMask.setGeometry(QtCore.QRect(160, 100, 221, 27))
        self.label_subnetMask.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_subnetMask.setText("")
        self.label_subnetMask.setObjectName("label_subnetMask")
        self.label_diaChi_3 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_3.setGeometry(QtCore.QRect(30, 80, 91, 20))
        self.label_diaChi_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_3.setObjectName("label_diaChi_3")
        self.label_currentIP = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_currentIP.setGeometry(QtCore.QRect(160, 70, 221, 27))
        self.label_currentIP.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 0, 0);\n"
"border-radius:3px")
        self.label_currentIP.setText("")
        self.label_currentIP.setObjectName("label_currentIP")
        self.label_ctThongTinCuavv_2 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_ctThongTinCuavv_2.setGeometry(QtCore.QRect(20, 34, 391, 21))
        self.label_ctThongTinCuavv_2.setStyleSheet("color: rgb(0, 85, 255);\n"
"font: 25 10pt \"Ubuntu\";")
        self.label_ctThongTinCuavv_2.setWordWrap(True)
        self.label_ctThongTinCuavv_2.setObjectName("label_ctThongTinCuavv_2")
        self.label_diaChi_7 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_7.setGeometry(QtCore.QRect(20, 10, 231, 17))
        self.label_diaChi_7.setStyleSheet("font: 75 bold 12pt \"Ubuntu\";")
        self.label_diaChi_7.setObjectName("label_diaChi_7")
        self.comboBox_choseIpMethod = QtWidgets.QComboBox(self.frame_autoShutdown_2)
        self.comboBox_choseIpMethod.setGeometry(QtCore.QRect(160, 176, 141, 31))
        self.comboBox_choseIpMethod.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox_choseIpMethod.setObjectName("comboBox_choseIpMethod")
        self.comboBox_choseIpMethod.addItem("")
        self.comboBox_choseIpMethod.addItem("")
        self.pushButton_setManualIP = QtWidgets.QPushButton(self.frame_autoShutdown_2)
        self.pushButton_setManualIP.setGeometry(QtCore.QRect(310, 170, 91, 41))
        self.pushButton_setManualIP.setStyleSheet("background-color: rgb(214, 214, 160);\n"
"border-radius:3px;\n"
"color: rgb(0, 170, 255);")
        self.pushButton_setManualIP.setObjectName("pushButton_setManualIP")
        self.label_diaChi_8 = QtWidgets.QLabel(self.frame_autoShutdown_2)
        self.label_diaChi_8.setGeometry(QtCore.QRect(30, 180, 121, 21))
        self.label_diaChi_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_diaChi_8.setObjectName("label_diaChi_8")

        self.retranslateUi(widget_containSettingContent)
        QtCore.QMetaObject.connectSlotsByName(widget_containSettingContent)
        widget_containSettingContent.setTabOrder(self.lineEdit_forInputIP, self.lineEdit_forInputPort)

    def retranslateUi(self, widget_containSettingContent):
        _translate = QtCore.QCoreApplication.translate
        widget_containSettingContent.setWindowTitle(_translate("widget_containSettingContent", "Form"))
        self.label_ctThongTinCuavv.setText(_translate("widget_containSettingContent", "(Thông tin của máy chủ trung tâm điều khiển thiết bị) "))
        self.label_diaChi.setText(_translate("widget_containSettingContent", "Địa chỉ IP"))
        self.label_cong.setText(_translate("widget_containSettingContent", "Cổng"))
        self.label_diaChi_2.setText(_translate("widget_containSettingContent", "Thông tin máy chủ"))
        self.pushButton_connectNewServer.setText(_translate("widget_containSettingContent", "Kết nối"))
        self.label_thongTinBoNho.setText(_translate("widget_containSettingContent", "Xóa toàn bộ dữ liệu"))
        self.label_ctBoNhoSuvv.setText(_translate("widget_containSettingContent", "(Xóa toàn bộ dữ liệu trên cảm biến)"))
        self.pushButton_deleteAllData.setText(_translate("widget_containSettingContent", "Xóa"))
        self.label_phienBanPhanMem.setText(_translate("widget_containSettingContent", "Phiên bản phần mềm"))
        self.label_ctPHanMemTrenvv.setText(_translate("widget_containSettingContent", "(Phần mềm của thiết bị)"))
        self.pushButton_checkUpdate.setText(_translate("widget_containSettingContent", "Kiểm tra cập nhật"))
        self.label_phienBan.setText(_translate("widget_containSettingContent", "Phiên bản:"))
        self.label_ngayGioCapNhat.setText(_translate("widget_containSettingContent", "Cập nhật ngày, giờ:"))
        self.label_banQuyen.setText(_translate("widget_containSettingContent", "Bản quyền:"))
        self.label_forShowFirmwareVersion.setText(_translate("widget_containSettingContent", "v0.0.0"))
        self.label_forShowCopyright.setText(_translate("widget_containSettingContent", "Công ty cổ phần Công nghệ và Kỹ thuật Ecotek"))
        self.label.setText(_translate("widget_containSettingContent", "HỆ THỐNG"))
        self.label_diaChi_6.setText(_translate("widget_containSettingContent", "Cổng mặc định"))
        self.label_diaChi_5.setText(_translate("widget_containSettingContent", "Mặt nạ "))
        self.label_diaChi_3.setText(_translate("widget_containSettingContent", "IP hiện tại"))
        self.label_ctThongTinCuavv_2.setText(_translate("widget_containSettingContent", "(Thông tin địa chỉ hiện tại của thiết bị)"))
        self.label_diaChi_7.setText(_translate("widget_containSettingContent", "Cài đặt IP thiết bị"))
        self.comboBox_choseIpMethod.setItemText(0, _translate("widget_containSettingContent", "Tự động"))
        self.comboBox_choseIpMethod.setItemText(1, _translate("widget_containSettingContent", "Thủ công"))
        self.pushButton_setManualIP.setText(_translate("widget_containSettingContent", "Cài đặt"))
        self.label_diaChi_8.setText(_translate("widget_containSettingContent", "Lấy IP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_containSettingContent = QtWidgets.QWidget()
    ui = Ui_widget_containSettingContent()
    ui.setupUi(widget_containSettingContent)
    widget_containSettingContent.show()
    sys.exit(app.exec_())
